name: Oyamatsumi
version: '0.1'
main: online.aruka.oyamatsumi.Oyamatsumi
api-version: '1.21'
softdepend:
  - GriefPrevention
  - WorldGuard
  - PlaceholderAPI

commands:
  miner:
    description: "Toggle bulk mining."
    usage: "/miner"
    permission: oyamatsumi.normal
    permission-message: "You do not have permission to use this command."

permissions:
  oyamatsumi.normal:
    description: "This is a bulk mining permission node."
    default: true