name: Oyamatsumi
version: '0.3'
main: online.aruka.oyamatsumi.Oyamatsumi
api-version: '1.21'

softdepend:
  - WorldGuard
  - PlaceholderAPI
  - CoreProtect

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:2.1.10"

commands:
  miner:
    description: "Toggle bulk mining."
    usage: "/miner"
    permission: oyamatsumi.normal
    permission-message: "You do not have permission to use this command."

permissions:
  oyamatsumi.normal:
    description: "This is a bulk mining permission node."
    default: true

  oyamatsumi.admin:
    description: "This is a Oyamatsumi admin permission node."
    default: op